name: Deploy React Test
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ./react/package-lock.json
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EM_ODDSEN24_TEST }}' > test-key.json
      - name: Use test project
        run: export GOOGLE_APPLICATION_CREDENTIALS=test-key.json && npx firebase-tools use em-oddsen24-test
      - name: Get config
        run: export GOOGLE_APPLICATION_CREDENTIALS=test-key.json && npx firebase-tools apps:sdkconfig web --json > ./react/src/firebase-config.json
      - run: cd ./react && npm ci && npm run build && cd ..
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EM_ODDSEN24_TEST }}
          channelId: live
          projectId: em-oddsen24-test
