name: Firebase Functions Deploy Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
    - name: Build
      run: cd ./functions && npm ci
    - name: Create SA key
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EM_ODDSEN24_TEST }}' > test-key.json
    - name: Use test project
      run: export GOOGLE_APPLICATION_CREDENTIALS=key.json && npx firebase-tools use em-oddsen24-test
    - name: Deploy
      run: export GOOGLE_APPLICATION_CREDENTIALS=test-key.json && npx firebase-tools deploy --only functions --json -f